### ISSUE TITLE
Question about fetch_dU_by_chrom.py

### ISSUE THREAD

**Issue by Zjianglin** [Jyyin333/Ucaps-seq#2]
Hi, professor Jin,
I'm trying to use `Ucaps-seq` to process our similar sequencing reads. 

First, I find that there seems to be an error in this script:
```
#Line 72 and Line 88
if sequence == None:
    continue
```
For the `Read 1` mapped to the first position of positive strand (read.reference_start is 0, `0-based` in `python`), the deduced `dU` location will be `[-1, 0)`, and the `fetch_sequence(fasta, chrom, start, end)` command will return a empty string (`""`) rather than `None`, so the `Line 72/88` will always be false and the result bed will contains regions with negative start sites (`-1`). Similar for the `Read 1` mapped to the last position of negative strand, the predicted `dU` site will be the 1-nt downstream of the read end. But there is no more base in reference sequence, so the  `fetch_sequence(fasta, chrom, start, end)` command will return a empty string (`""`)  as well. Therefor, I suggest that the judgement command may be changed to `if len(sequence) != 1` or `if not (sequence.upper() in ('A', 'C', 'G', 'T'))` .

Second, I'm confused about some filter commands in the script and their relationships with your description in the paper. Could you please give me some interpretatioon?
*paper*:` c) paired-end reads are not in a proper pair in the genome; d) second read in a pair; e) 5’-end of Read 1 includes customized adaptor sequence. `
*fetch_dU_by_chrom.py*:
```
# fetch and filter reads
    for read in samfile.fetch(chrom):   
        if read.is_read2:
            continue
        if read.is_unmapped:
            continue
        if read.mate_is_unmapped:
            continue
        if not read.is_proper_pair:
            continue
        if read.is_secondary:
            continue
        if read.mapping_quality < 60:
            continue

```

Third, We have build the library and sequenced a dataset with 'dU spike in ' sequence. The '48-th' nucleotide of the `dU spike in` sequence is a `dU`. We can see an obvious truncated edge in dereped `bam` file. However, there is no valid sequence in the output of the `snakemake` pipeline (`HEK293T` pipeline, output is `XXX.merged.sort.bam`). Here is the IGV view, could you please help me for this occasion? It's confused.
top half panel is `XXX_sorted_dedup.bam` view and bottom half panel is `XXX.merged.sort.bam`:
![Screenshot from 2022-10-14 17-49-13](https://user-images.githubusercontent.com/14870842/195818491-c31b62d7-82e6-49b6-8b2b-ddef64f7e0a2.png)

Thanks and looking forward to your reply.

**Comment by Jyyin333** [comment]
Hi, Zjianglin:
        Q1:
        Thanks for your suggestions. But the first thing i want to say is that this is not a mistake. In this run, only one bp was considered and Ucapseq are highly specific so abnormalities are rare(Compared to our [another study](https://github.com/Jyyin333/CLAPS-seq/blob/main/Scripts/OG_damage_fetch_by_chrom.py) where we expanded the selection region). Also, in masked genome, most chromsomes are start/end with "N", it's hard to occur what you are worried just like `reference_start is 0`.  But you can add this line `len(seq)!=1` to your own script to improve accuracy.
        Q2:
        you should read some help documents carefully, such as [SAM-specification](https://samtools.github.io/hts-specs/SAMv1.pdf) ,[Pysam](https://pysam.readthedocs.io/en/latest/api.html#api)... BTW, the code `re.match(".*\d+S$", read.cigarstring)` was used to remove unwanted reads which carried adapters.
        Q3:
        It's hard to give some useful advice just a screenshot was given. I think you should extract the reads located in 48-th and see what was happened before or after filtering, are this duplicates? or low quality? ... then you can try to lower the filtering standards.

**Comment by Zjianglin** [comment]
Hi @Jyyin333 , thanks for your timely reply. 

As you mentioned, the `Q1` situation is rare. I encountered the negative start position errors when I add `chrY, chrM, and dU spike in` chromosomes into `fetch_dU_by_chrom` script. I have add the 'len(seq) != 1' to my code.

For the screenshot, I found that most mapped reads were filtered out because they are `Read2`. Could you please help me why this happened? BTW,  why you only used `Read1` to identify `dU` sites in your initial scripts?

Thanks.

**Comment by Jyyin333** [comment]
sorry I missed this question. Only read1 was considered because of Illumina's sequencing strategy. In this situation, R1 can capture the potential targets but R2 cannot so it needs to be removed.
