### ISSUE TITLE
Output of fetch_dU_by_chrom.py

### ISSUE THREAD

**Issue by jayneAbarbour** [Jyyin333/Ucaps-seq#3]
I have run your pipeline on the Hela cell data and am not clear on exactly what the output of single base resolution dU means after running fetch_dU_by_chrom.py. The resulting bed files for all samples including input have around 10 million sites
Why are the input samples so high? Do the bed files need to be filtered in some way to identify dU?

**Comment by Jyyin333** [comment]
Hi, jayneAbarbour:
	thanks for your question.
	In our study, HeLa cells treated with PMX were used to demonstrate the feasibility of Ucaps-seq in mammalian genome.  On the one hand, as the dU frequency in wild type Hela cells is so rare that our  method was not able to detect the dU in WT Hela cells; the other, HeLa cells were sequenced shallowly so it was not appropriate for genuine dU identification. 
        As for your doubts, first of all this script just simply trim some unwanted reads (low mapping quality, Read2, secondary…) to get the candidates, therefore the results need to be further filtered. After run `fetch_dU_by_chrom.py` , the input still quite different from treated sample although it has a lot of records and mainly reflected in the base composition (refer to Fig3A). Because dU is too sparse across the genome to be detected, it is difficult to accurately identify dU. As you can see from the processing of [HEK293](https://github.com/Jyyin333/Ucaps-seq/blob/main/HEK293T.md), we sequenced the cells in depth, screened the results through customized methods( FigS5D), and finally validated them by amplicon PCR.

**Comment by jayneAbarbour** [comment]
Thank you kindly for your reply
